Pim first br
uashogeschoolutrecht/SEAA pull request #4
Opened 2023-12-07 10:42 UTC by PimLamberts

Eerste versie werkende code. Initiële opschoning NSE antwoorden verloopt naar wens: code kan op basis van geïmporteerde woordenlijst aangeven welke antwoorden potentieel AVG gevoelig zijn en geeft aan om welke woorden het gaat. 
Verdere processingstappen vereist om de precisie te verhogen. Bijvoorbeeld door spelfouten als gevolg van accenten en trema's over te slaan.

2023-12-08 09:27 UTC, Fraukje commented on main.py
>  nseant_df['AVG_gevoelig'] = 0
Zou je deze standaard op 1 willen zetten? Dus: voordat we beginnen gaan we er vanuit dat alles AVG gevoelige informatie bevat, en we gaan bewijzen dat dit voor een aantal gevallen niet zo is.

2023-12-08 09:35 UTC, Fraukje requested changes
Super de toevoegingen op de README en ziet er mooi uit in de main! Ik vind het prettig lezen hoe je overal comments bij het gezet wat je doet en ook niet gelijk 10 dingen tegelijk doet maar stap voor stap. Ook handig dat je met een sample van de data werkt. 

In de main stel ik 2 inhoudelijke changes voor: ik zou namelijk er in het begin van uit willen gaan dat álles AVG-gevoelige informatie bevat. En dan met behulp van het SEAA algoritme stuk voor stuk antwoorden op 0 gaan zetten (nu gebeurt dat andersom). Vanuit de AVG heet dit 'Privacy by design'

Daarnaast: zou je variabelen etc. die nu Nederlandse termen hebben, bijv. 'gevoelige_woorden' in het Engels willen vertalen? Ons grote einddoel is het uitrollen van dit algoritme HU-breed en de ervaring leert dat Data Scientist zeer vaak Engelstalig zijn.

2023-12-11 16:38 UTC, PimLamberts commented
@Fraukje, bedankt voor de feedback. Alles is verwerkt en gecommit!

2023-12-13 09:40 UTC, Fraukje approved these changes
Nice! Ben helemaal akkoord en ga je wijzigingen naar main mergen

2023-12-13 09:41 UTC, merged

2023-12-13 09:42 UTC, Fraukje commented
@PimLamberts Normaliter zou ik deze branch nu verwijderen, maar mogelijk heb je nog wijzigingen lokaal staan op deze branch? Als het je lukt: deze branch hier deleten, en een nieuwe branch aanmaken voor jezelf vanaf main en daar weer nieuwe wijzigingen op gaan doen!

2023-12-13 09:46 UTC, PimLamberts commented
@Fraukje Cool, m'n eerste merge! Ik heb verder geen wijzigingen doorgevoerd dus ik zal deze verwijderen en een nieuwe aanmaken.